app/models.py
from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime


class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    hashed_password = db.Column(db.String(120), nullable=False)

    blogs = db.relationship("Blog", backref="author", lazy="dynamic")

    def set_password(self, password):
        self.hashed_password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.hashed_password, password)


class Blog(db.Model):
    __tablename__ = "blogs"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, server_default=db.func.now())

    author_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)

    def to_dict(self):
        return {
            "id": self.id,
            "title": self.title,
            "content": self.content,
            "author": {
                "id": self.author.id,
                "username": self.author.username,
            },
            "created_at": datetime.fromisoformat(self.created_at.isoformat()).strftime(
                "%d %b %Y at %H:%M:%S"
            ),
        }

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length


class BlogForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(max=200)])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Submit")


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Submit")

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

__version__ = "1.0.0"

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config.from_object("config.Config")
    db.init_app(app)

    from app.routes import routes_bp
    from app.auth import auth_bp

    app.register_blueprint(routes_bp)
    app.register_blueprint(auth_bp)

    print(f" * Current version: {__version__}")

    return app

app/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, session
from app.forms import LoginForm
from app.models import User


auth_bp = Blueprint("auth", __name__)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            session["user_id"] = user.id
            flash("Logged in successfully.", "success")
            return redirect(url_for("blogs.get_blogs"))
        else:
            flash("Invalid username or password.", "danger")
    return render_template("login.html", form=form)


@auth_bp.route("/logout")
def logout():
    session.pop("user_id", None)
    flash("You have been logged out.", "info")
    return redirect(url_for("blogs.get_blogs"))

app/routes.py
from flask import Blueprint, flash, request, render_template, redirect, url_for

from app.models import Blog, User
from app.forms import BlogForm
from app.utils import login_required

from . import db

routes_bp = Blueprint("blogs", __name__)


@routes_bp.route("/new", methods=["GET", "POST"])
@login_required
def create_blog():
    form = BlogForm()
    if form.validate_on_submit():
        user = User.query.first()

        blog = Blog(
            title=request.form.get("title"),
            content=request.form.get("content"),
            author_id=user.id,
        )

        db.session.add(blog)
        db.session.commit()

        data = blog.to_dict()

        flash("Blog created successfully", "success")
        return render_template("blog_details.html", blog=data)
    return render_template("create_blog.html", form=form)


@routes_bp.route("/", methods=["GET"])
def get_blogs():
    blogs = Blog.query.all()
    blogs = [blog.to_dict() for blog in blogs]
    return render_template("index.html", blogs=blogs)


@routes_bp.route("/<int:blog_id>", methods=["GET"])
def get_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    data = blog.to_dict()
    return render_template("blog_details.html", blog=data)


@routes_bp.route("/delete/<int:blog_id>", methods=["POST"])
@login_required
def delete_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)

    db.session.delete(blog)
    db.session.commit()

    flash("Blog deleted successfully", "success")
    return redirect(url_for("blogs.get_blogs"))


@routes_bp.route("/edit/<int:blog_id>", methods=["POST", "GET"])
@login_required
def update_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    form = BlogForm(obj=blog)

    if form.validate_on_submit():
        blog.title = form.title.data
        blog.content = form.content.data
        db.session.commit()
        flash("Blog updated successfully", "success")
        return redirect(url_for("blogs.get_blog", blog_id=blog.id))

    return render_template("update_blog.html", form=form, blog=blog)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{% block title %}AElalfee Blogs{% endblock %}</title>
        <meta name="description" content="AElalfee's personal blog" />
        <meta name="author" content="AElalfee" />
        <meta name="keywords" content="blog, personal, AElalfee" />

        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
            rel="stylesheet"
        />

        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='style.css') }}"
        />

        {% block head %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('blogs.get_blogs') }}">AElalfee Blogs</a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("blogs.get_blogs")}}">Home</a>
                        </li>
                        {% if session.get("user_id") %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("blogs.create_blog") }}">New Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %} {%
            if messages %} {% for category, message in messages %}
            <div
                class="alert alert-{{ category }} alert-dismissible fade show"
                role="alert"
            >
                {{ message }}
                <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="alert"
                    aria-label="Close"
                ></button>
            </div>
            {% endfor %} {% endif %} {% endwith %} {% block content %}{%
            endblock %}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"></script>

        {% block scripts %}{% endblock %}
    </body>
</html>

app/templates/blog_details.html
{% extends "base.html" %} {% block title %}{{ blog.title }}{% endblock %} {%
block content %}
<div class="container mt-4">
    <h1>{{ blog.title }}</h1>
    <p class="text-muted">
        By {{ blog.author.username }} | {{ blog.created_at }}
    </p>

    <hr />

    <div class="blog-content">{{ blog.content | safe }}</div>

    <hr />

    <a href="{{ url_for('blogs.get_blogs') }}" class="btn btn-secondary"
        >Back to all blogs</a
    >
    {% if session.get("user_id")%}
    <a
        href="{{ url_for('blogs.update_blog', blog_id=blog.id) }}"
        class="btn btn-warning"
        >Edit</a
    >

    <form
        action="{{ url_for('blogs.delete_blog', blog_id=blog.id) }}"
        method="POST"
        style="display: inline-block"
        onsubmit="return confirm('Are you sure you want to delete this blog?');"
    >
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    {% endif %}
</div>
{% endblock %}

app/templates/create_blog.html
{% extends "base.html" %} {% block title %}Create New Blog{% endblock %} {%
block content %}
<div class="container mt-4">
    <h2>Create New Blog Post</h2>

    <form method="POST" action="{{ url_for('blogs.create_blog') }}">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.title.label(class="form-label") }} {{
            form.title(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.content.label(class="form-label") }} {{
            form.content(class="form-control", rows=6) }}
        </div>

        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block title %}Blog Home{% endblock %} {% block
content %}
<h1 class="mb-4">All Blog Posts</h1>

{% if blogs %}
<div class="list-group">
    {% for blog in blogs %}
    <a
        href="{{ url_for('blogs.get_blog', blog_id=blog.id) }}"
        class="list-group-item list-group-item-action"
    >
        <h5 class="mb-1">{{ blog.title }}</h5>
        <small
            >By {{ blog.author.username if blog.author.username else 'Unknown
            Author' }}</small
        >
        <p class="mb-1 text-truncate">{{ blog.content }}</p>
    </a>
    {% endfor %}
</div>
{% else %}
<p>
    No blog posts available. {% if session.get('user_id') %}
    <a href="{{ url_for('blogs.create_blog') }}">Create one now!</a>
    {% endif %}
</p>
{% endif %} {% endblock %}

app/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<div class="container mt-4">
    <h2>Login</h2>
    <form method="POST" action="{{ url_for('auth.login') }}">
        {{ form.hidden_tag() }}

        <div class="mb-3">
            {{ form.email.label(class="form-label") }} {{
            form.email(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.password.label(class="form-label") }} {{
            form.password(class="form-control") }}
        </div>

        {{ form.submit(class="btn btn-primary") }}
    </form>
</div>
{% endblock %}

app/templates/update_blog.html
{% extends "base.html" %} {% block title %}Edit Blog{% endblock %} {% block
content %}
<div class="container mt-4">
    <h2>Edit Blog</h2>

    <form
        method="POST"
        action="{{ url_for('blogs.update_blog', blog_id=blog.id) }}"
    >
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.title.label(class="form-label") }} {{
            form.title(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.content.label(class="form-label") }} {{
            form.content(class="form-control", rows=6) }}
        </div>

        {{ form.submit(class="btn btn-primary") }}
        <a
            href="{{ url_for('blogs.get_blog', blog_id=blog.id) }}"
            class="btn btn-secondary"
            >Cancel</a
        >
    </form>
</div>
{% endblock %}